name: empire_env
channels:
  - conda-forge
  - defaults
  - gurobi
dependencies:
  - cloudpickle == 3.0.0
  - openpyxl==3.1.5
  - pandas==2.2.2
  - pyomo==6.7.3
  - pyyaml==6.0.2
  - glpk>=4.65
  - gurobi
  - python==3.11
  - scipy==1.14.0
  - scikit-learn==1.5.1
  - matplotlib==3.9.2
  
  # For the streamlit app
#  - streamlit
#  - plotly
#  - networkx

  # Docs
#  - furo 
#  - sphinx

  # Dev tools
#  - pytest
#  - ruff
  
  - pip
  - pip:
      - -e . # Install empire as pip package in editable mode
      - streamlit-authenticator